# Set command prompt options
PS1="\n\u @\h [\d \@]\n\w "

# Enable command prompt coloring
export CLICOLOR=1

# Set vim as default editor
export EDITOR='vim'

# Enable vi mode in shell
set -o vi

# Enable iTerm2 shell integration
source /Users/christopherwatson/.iterm2_shell_integration.bash

# Enable Homebrew-installed bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Enable aws-cli bash completion
complete -C aws_completer aws

# Enable t completion (Twitter CLI client)
. ~/t/etc/t-completion.sh

# Enable z (intelligent directory autojumping)
. `brew --prefix`/etc/profile.d/z.sh

# Enable nvm
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# nvm node version shortcuts
alias ns="nvm use system"
alias n10="nvm use 0.10"
alias n12="nvm use 0.12"
alias nio="nvm use iojs"

# List top-level npm global modules
alias "ng"="npm -g ls --depth=0"

# List top-level npm local modules
alias "nl"="npm ls --depth=0"

# Golang env variables
export GOPATH=/Users/christopherwatson/go/
export GOBIN=$GOPATH/bin
export PATH=$GOPATH/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

# Enable Halcyon
eval "$( HALCYON_NO_SELF_UPDATE=1 "/app/halcyon/halcyon" paths )"

# Copy all .jpg, .jpeg and .png images in current directory to webimages "pre" folder
alias ci="cp *.jpg ~/webimages/pre; cp *.png ~/webimages/pre; cp *.jpeg ~/webimages/pre"

# Run all Imageoptim-CLI operations on images in "pre" folder and move output to "post"
alias oi="imageoptim -j -a -q -d ~/webimages/pre && mv ~/webimages/pre/* ~/webimages/post"

# Quickly edit dotfiles
alias bp="vim ~/.bash_profile"
alias br="vim ~/.bashrc"
alias tc="vim ~/.tmux.conf"
alias vr="vim ~/.vimrc"

# Backup OSX dotfiles to local directory
alias dfb="cd ~/; cp ~/.bashrc .bash_profile .tmux.conf .vimrc ~/localdotfilesbackup"

# Force delete trash
alias te="sudo rm -rf ~/.Trash/*"

# Navigate backwards in directories
alias ..="cd .."
alias ...="cd ../../../"
alias ....="cd ../../../../"
alias .....="cd ../../../../../"
alias ......="cd ../../../../../../"

# Go back to previous directory
alias b="cd - "

# Clear scrollback (works with tmux)
alias c="clear"

# Go to Downloads directory
alias dl="cd ~/Downloads"

# Go to Desktop directory
alias dt="cd ~/Desktop"

# Open current directory in Finder
alias f="open ."

# Clone Ghost master repo
alias gcgm="git clone git@github.com:TryGhost/Ghost.git"

# Clone Ghost stable repo
alias gcgs="git clone -b stable git@github.com:TryGhost/Ghost.git"

# Test Ghost pull requests
alias gpr='f() { git fetch upstream && git checkout pr/"$1" && npm install && grunt init && npm start; }; f'

# Go to Ghost-Vagrant-Shell folder
alias gvs='cd ~/Ghost-Vagrant-Shell'

# Required for awesome undo program: https://github.com/nvbn/thefuck
alias fuck='$(thefuck $(fc -ln -1))'

# Go to Home directory
alias h="cd ~/"

# Quicker ls
alias l="ls"

# Whoops! ls typo
alias sl="ls"

# Verbose ls
alias la="ls -la"

# List hidden files
alias lh="ls -d .*"

# Reload shell
alias r=". ~/.bashrc"

# Start tmuxinator server session
alias s="mux servers"

# Quicker vim
alias v="vim"

# Exit shell
alias x="exit"

# Go to writing folder
alias w="cd ~/writing"

# Daily update (run all below)
alias du="bu && gu && nu && pu && ru && vp"

# Run all Homebrew operations
alias bu="brew update; brew upgrade; brew cleanup; brew cask cleanup; brew prune; brew doctor"

# Update all Go packages
alias gu="go get -u all"

# Update global node packages
alias nu="npm -g update"

# Update and cleanup all Python packages
alias pu="yolk --upgrade"

# Update and cleanup all Ruby gems
alias ru="gem update; gem cleanup"

# Install, clean up, and update Vim plugins via Vundle
alias vp="vim +PluginInstall +qall; vim +PluginClean +qall; vim +PluginUpdate +qall"
