set nocompatible

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'bling/vim-airline'
Plugin 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'dbakker/vim-lint'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'kien/ctrlp.vim'
Plugin 'mhinz/vim-signify'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'othree/html5.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'

call vundle#end()
filetype plugin indent on

" Automatically reload .vimrc when saved
augroup reload_vimrc " {
	autocmd!
	autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

" Enable 256 colors in terminal
set t_Co=256

" Remap Escape key to home row
imap jk <esc>

" Remap leader key to space bar
let mapleader=" "

" Navigate by visual rather than actual lines
nnoremap k gk
nnoremap j gj
nnoremap gk k
nnoremap gj j

" Enable syntax highlighting
syntax enable

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Open new split panes to right and bottom
set splitbelow
set splitright

" Press Enter after searching to remove result highlighting
nnoremap <CR> :noh<CR><CR>

" Enable Airline Powerline symbols
let g:airline_powerline_fonts = 1

" Invoke CtrlP with CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" Quickly strip whitespace
nnoremap <leader>w :StripWhitespace<CR>

" Core non-plugin Vim settings
set autoindent								  " Indent at the same level of the previous line
set autoread										" Automatically recognize when a file is changed outside of vim
set backspace=indent,eol,start	" Make backspace behave normally
set clipboard=unnamed
set encoding=utf8
set history=1000
set hlsearch                    " Highlight search results
set ignorecase                  " Case-insensitive-search
set incsearch                   " Find as you type search
set laststatus=2
set lazyredraw
set nobackup
set nowritebackup
set noswapfile
set noshowmode
set number
set relativenumber
set ruler
set shiftwidth=2
set showcmd
set showmatch
set nobackup
set softtabstop=2
set smartcase
set smartindent
set smarttab
set tabstop=2
set ttyfast
set undolevels=1000
set undoreload=1000
set wildmenu
set wildmode=list:longest,full
